# -*- coding: utf-8 -*-
"""Introducao a biblioteca Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x3eVjtayAajGashHn3eyjCrB_V8FPsuj
"""

#Importando a biblioteca Pandas
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets/Gapminder.csv', error_bad_lines=False,sep=';') #Ignorar linhas com erro
#Lendo ;

#Visualizando as 5 primeiras linhas
df.head()

#Alterando nome das Colunas
df = df.rename(columns={'country':'Pais', 'continent':'Continente', 'year':'Ano', 'lifeExp':'Expectativa de Vida', 'Pop':'Populacao Total', 'gdpPercap':'PIB'})
df.head(10) # Por default é 5, mas podemos colocar o qualto queiser

#Total de linhas e colunas
df.shape

#Retonar apenas nomes das colunas
df.columns

#saber o tipo de dados em cada coluna
df.dtypes

#Retorna as ultimas linhas
df.tail()

#Retorna as ultimas 9 linhas
df.tail(9)

#Retorna informacoes estatisticas
df.describe()

#Retorna valores unicos da coluna
df['Continente'].unique()

Asia = df.loc[df['Continente'] == 'Asia']
Asia

#Agrupamento de Dados
df.groupby('Continente')['Pais'].nunique()

#Expectativa de Vida Media por Pais
df.groupby('Ano')['Expectativa de Vida'].mean()

#Media Bruta
df['PIB'].mean()

#Soma
df['PIB'].sum()

