# -*- coding: utf-8 -*-
"""Python Básico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PLHwntAkBA1L9N_xh5fvpfYbTN5LHk04
"""

print('Olá Mundo')

print('Estou aprendendo Python')

'Estou aprendendo Python'

#Soma
1 + 1

#Subtração
10 - 2

#Esse é um comentário em python

#Multiplicação
8 * 9

#Divisão
10/2

a = 4
b = 6

a + b

#Criando uma variavel do tipo string
frase = 'Python para análise de dados'

frase[0]

frase[0:10]

frase[10:]

frase[:17]

frase.count('dados')

frase.lower()

frase.upper()

frase.replace('Python', 'Substituir')

